name: Add tag on merge to main

on:
  pull_request:
    types: [closed]

jobs:
  add-tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add tag
        run: |
          tag_name="PR-${{ github.event.pull_request.title }}"
          git tag -a $tag_name -m "Tag added on PR merge"
          git push origin $tag_name
